---
- name: Run sosreport on remote host
  hosts: all
  become: yes
  tasks:
    - name: Ensure sosreport is installed
      package:
        name: sos
        state: present

    - name: Create tmp sosreports directory
      file:
        path: /tmp/sosreports
        state: directory
        mode: '0755'

    - name: Run sosreport command
      command: "sos report --batch --case-id={{ case_id }} --tmp-dir=/tmp/sosreports"
      register: sosreport_output
      ignore_errors: yes

    - name: Show sosreport output
      debug:
        msg: "{{ sosreport_output.stdout }}"
        
    - name: Check if sosreport command was successful
      debug:
        msg: "sosreport completed successfully!"
      when: sosreport_output.rc == 0

    - name: Handle sosreport failure
      debug:
        msg: "sosreport failed to run!"
      when: sosreport_output.rc != 0

    - name: Create local dir to store sos-reports
      file:
        path: /tmp/sosreports
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Find the sosreport archive file
      find:
        paths: /tmp/sosreports
        patterns: "*{{ case_id }}-*.tar.xz"
      register: found_files
      when: sosreport_output.rc == 0

    - name: Show found sosreport files
      debug:
        msg: "{{ found_files.files }}"
      when: found_files.matched > 0

    - name: Copy the sosreport archive to local machine
      fetch:
        src: "{{ item.path }}"
        dest: "/tmp/sosreport/"
        flat: yes
      with_items: "{{ found_files.files }}"
      when: 
      - found_files.matched > 0                      
      - sosreport_output.rc == 0
